apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-frontend
  template:
    metadata:
      labels:
        app: crm-frontend
    spec:
      containers:
        - name: crm-frontend
          image: crm-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crm-frontend-service
spec:
  selector:
    app: crm-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Porta exposta no host para acesso via localhost
  type: NodePort
