# Generated by Django 5.1.7 on 2025-04-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venda_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='Valor',
            new_name='valor',
        ),
    ]
